"""
Token Tracking - Base Class

Why this exists:
Every LLM provider reports token usage differently. As an example,
Azure/OpenAI calls them "prompt_tokens" and "completion_tokens".
Anthropic calls them "input_tokens" and "output_tokens". Some local
or third-party providers don't report usage at all and you'd have to
estimate it yourself with a tokenizer library.

Rather than have every part of the codebase know about each
provider's specific field names, we normalize all of that into ONE
shape right here, and every other provider-specific tracker (like
AzureTokenTracker) is responsible for translating ITS provider's
raw usage dict into this shape before recording it.

That means the rest of the app (the chat route, any future
dashboards, billing reports, etc.) only ever needs to know about
this one normalized shape, never about Azure's or Anthropic's or
anyone else's specific field names.
"""

from abc import ABC, abstractmethod
from dataclasses import dataclass, field
from datetime import datetime, timezone


def cached_tokens_from(raw_usage: dict) -> int:
    """Cached prompt tokens, wherever the provider hid them.

    Azure/OpenAI nest this under `prompt_tokens_details.cached_tokens`.
    It is a SUBSET of `prompt_tokens`, never an addition to it — a long agent
    run re-sends most of its prompt every step, so this is usually the majority
    of the tokens and a fraction of the bill.
    """
    details = raw_usage.get("prompt_tokens_details") or {}
    if isinstance(details, dict) and details.get("cached_tokens") is not None:
        return int(details.get("cached_tokens") or 0)
    return int(raw_usage.get("cached_tokens", 0) or 0)


def reasoning_tokens_from(raw_usage: dict) -> int:
    """Hidden reasoning tokens (gpt-5 / o-series). Billed as output and
    invisible in the response text, which is why completion_tokens alone can
    look inexplicably large."""
    details = raw_usage.get("completion_tokens_details") or {}
    if isinstance(details, dict):
        return int(details.get("reasoning_tokens", 0) or 0)
    return 0


@dataclass
class TokenUsage:
    """
    The normalized shape every provider's usage gets translated into.

    prompt_tokens:     tokens used by the input (system + user + history)
    completion_tokens: tokens generated by the model in its response
    total_tokens:      sum of the two - stored separately rather than
                        always recomputed, because some providers might
                        report a total that doesn't exactly equal the
                        sum (e.g. due to internal reasoning tokens),
                        and we want to record what the provider actually
                        said, not assume.
    cached_tokens:     the portion of prompt_tokens that hit the provider's
                        prompt cache. A SUBSET of prompt_tokens, not an
                        addition to them - Azure reports it nested inside
                        prompt_tokens_details. It matters because cached
                        input is billed at a small fraction of the fresh
                        rate, so a long agent run's real cost is nothing
                        like prompt_tokens x the headline price.
    reasoning_tokens:  hidden reasoning tokens (gpt-5 / o-series). Billed as
                        output, invisible in the response text, which is why
                        completion_tokens alone can look inexplicably large.
    cost_usd:          what this call actually cost, priced from the model's
                        own rates. Zero when no pricing is configured.
    model:             which model/deployment actually served this call.
                        Useful once you have more than one model in play,
                        since cost-per-token differs by model.
    timestamp:          when this usage was recorded (UTC), so usage can
                        later be grouped by day/hour for reporting.
    """
    prompt_tokens: int = 0
    completion_tokens: int = 0
    total_tokens: int = 0
    cached_tokens: int = 0
    reasoning_tokens: int = 0
    cost_usd: float = 0.0
    model: str = "unknown"
    timestamp: str = field(
        default_factory=lambda: datetime.now(timezone.utc).isoformat()
    )

    def to_dict(self):
        return {
            "prompt_tokens": self.prompt_tokens,
            "completion_tokens": self.completion_tokens,
            "total_tokens": self.total_tokens,
            "cached_tokens": self.cached_tokens,
            "reasoning_tokens": self.reasoning_tokens,
            "cost_usd": self.cost_usd,
            "model": self.model,
            "timestamp": self.timestamp,
        }


class BaseTokenTracker(ABC):
    """
    Every provider-specific tracker (AzureTokenTracker, etc.) must
    extend this class.

    The contract is simple:
      1. record_usage() takes whatever raw usage dict that specific
         provider's API returned, normalizes it into a TokenUsage,
         stores it, and returns the normalized TokenUsage so the
         caller can use it immediately (e.g. to send it down to the
         client in an SSE event).
      2. get_total() and get_history() let anything else in the app
         (a dashboard, a /usage endpoint, logging) read back what's
         been tracked so far, without needing to know how it was
         stored internally.

    This class keeps everything in memory (a plain Python list) by
    default. That's intentional and matches how this project keeps
    conversation history in memory too - if you need this to persist
    across restarts later, you'd extend this same way LongTermMemory
    extends ShortTermMemory: same interface, swap the storage.
    """

    def __init__(self):
        self._history: list[TokenUsage] = []

    @abstractmethod
    def record_usage(self, raw_usage: dict, model: str = "unknown") -> TokenUsage:
        """
        Take the RAW usage dict exactly as that provider's API
        returned it (different field names per provider - that's the
        whole reason this method is abstract) and turn it into a
        normalized TokenUsage. Store it, and return it.
        """
        pass

    def get_history(self) -> list[dict]:
        """
        Return every recorded usage entry as plain dicts, in the
        order they were recorded (oldest first). Useful for showing
        a full usage log, or for exporting to a file/database later.
        """
        return [usage.to_dict() for usage in self._history]

    def get_total(self) -> dict:
        """
        Sum up every usage entry recorded so far into one combined
        total. This is what you'd show as "tokens used this session"
        or "tokens used today" in a simple dashboard.
        """
        total_prompt = sum(u.prompt_tokens for u in self._history)
        total_completion = sum(u.completion_tokens for u in self._history)
        total_overall = sum(u.total_tokens for u in self._history)
        total_cached = sum(u.cached_tokens for u in self._history)
        total_cost = sum(u.cost_usd for u in self._history)

        return {
            "prompt_tokens": total_prompt,
            "completion_tokens": total_completion,
            "total_tokens": total_overall,
            "cached_tokens": total_cached,
            "cost_usd": round(total_cost, 6),
            "request_count": len(self._history),
        }

    def reset(self):
        """
        Clear all recorded usage. Useful for tests, or if you want
        to track usage per-conversation rather than for the whole
        process lifetime (call reset() when a new conversation starts).
        """
        self._history = []
