-- This script was generated by the ERD tool in pgAdmin 4.
-- Please log an issue at https://github.com/pgadmin-org/pgadmin4/issues/new/choose if you find any bugs, including reproduction steps.
BEGIN;


CREATE TABLE IF NOT EXISTS public.agent_checkpoints
(
    id bigserial NOT NULL,
    tracking_id text COLLATE pg_catalog."default" NOT NULL,
    thread_id text COLLATE pg_catalog."default" NOT NULL,
    agent_id text COLLATE pg_catalog."default" NOT NULL,
    parent_agent_id text COLLATE pg_catalog."default",
    role text COLLATE pg_catalog."default",
    task text COLLATE pg_catalog."default",
    status text COLLATE pg_catalog."default" NOT NULL,
    messages_json jsonb NOT NULL,
    usage jsonb NOT NULL DEFAULT '{}'::jsonb,
    steps_taken integer NOT NULL DEFAULT 0,
    created_at timestamp with time zone NOT NULL DEFAULT now(),
    updated_at timestamp with time zone NOT NULL DEFAULT now(),
    CONSTRAINT agent_checkpoints_pkey PRIMARY KEY (id),
    CONSTRAINT agent_checkpoints_thread_id_agent_id_key UNIQUE (thread_id, agent_id)
);

CREATE TABLE IF NOT EXISTS public.agent_messages
(
    id bigserial NOT NULL,
    tracking_id text COLLATE pg_catalog."default" NOT NULL,
    role character varying(50) COLLATE pg_catalog."default" NOT NULL,
    content text COLLATE pg_catalog."default",
    tool_calls jsonb,
    tool_call_id text COLLATE pg_catalog."default",
    created_at timestamp with time zone NOT NULL DEFAULT now(),
    CONSTRAINT agent_messages_pkey PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS public.agent_session_snapshots
(
    id bigserial NOT NULL,
    tracking_id text COLLATE pg_catalog."default" NOT NULL,
    messages_json jsonb NOT NULL,
    created_at timestamp with time zone NOT NULL DEFAULT now(),
    CONSTRAINT agent_session_snapshots_pkey PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS public.chat_messages
(
    id bigserial NOT NULL,
    workspace_id bigint NOT NULL,
    session_id bigint,
    role character varying(50) COLLATE pg_catalog."default" NOT NULL,
    content text COLLATE pg_catalog."default" NOT NULL,
    metadata jsonb NOT NULL DEFAULT '{}'::jsonb,
    created_at timestamp with time zone NOT NULL DEFAULT now(),
    CONSTRAINT chat_messages_pkey PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS public.connectors
(
    id bigserial NOT NULL,
    workspace_id bigint NOT NULL,
    connector_type character varying(50) COLLATE pg_catalog."default" NOT NULL,
    display_name character varying(255) COLLATE pg_catalog."default",
    metadata jsonb NOT NULL DEFAULT '{}'::jsonb,
    status character varying(20) COLLATE pg_catalog."default" NOT NULL DEFAULT 'active'::character varying,
    version integer NOT NULL DEFAULT 1,
    created_at timestamp with time zone NOT NULL DEFAULT now(),
    updated_at timestamp with time zone NOT NULL DEFAULT now(),
    deleted_at timestamp with time zone,
    CONSTRAINT connectors_pkey PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS public.long_term_memory
(
    id bigserial NOT NULL,
    tracking_id text COLLATE pg_catalog."default" NOT NULL,
    content text COLLATE pg_catalog."default" NOT NULL,
    tags jsonb NOT NULL DEFAULT '[]'::jsonb,
    created_at timestamp with time zone NOT NULL DEFAULT now(),
    CONSTRAINT long_term_memory_pkey PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS public.run_states
(
    tracking_id text COLLATE pg_catalog."default" NOT NULL,
    state jsonb NOT NULL,
    created_at timestamp with time zone NOT NULL DEFAULT now(),
    updated_at timestamp with time zone NOT NULL DEFAULT now(),
    CONSTRAINT run_states_pkey PRIMARY KEY (tracking_id)
);

CREATE TABLE IF NOT EXISTS public.session_state
(
    id bigserial NOT NULL,
    workspace_id bigint NOT NULL,
    session_id bigint,
    state_json jsonb NOT NULL DEFAULT '{}'::jsonb,
    version integer NOT NULL DEFAULT 1,
    created_at timestamp with time zone NOT NULL DEFAULT now(),
    updated_at timestamp with time zone NOT NULL DEFAULT now(),
    CONSTRAINT session_state_pkey PRIMARY KEY (id),
    CONSTRAINT uq_session_state_workspace UNIQUE (workspace_id)
);

CREATE TABLE IF NOT EXISTS public.sessions
(
    id bigserial NOT NULL,
    workspace_id bigint NOT NULL,
    user_id integer NOT NULL,
    session_name character varying(255) COLLATE pg_catalog."default" NOT NULL,
    status character varying(20) COLLATE pg_catalog."default" NOT NULL DEFAULT 'active'::character varying,
    is_active boolean NOT NULL DEFAULT false,
    context_snapshot jsonb NOT NULL DEFAULT '{}'::jsonb,
    created_at timestamp with time zone NOT NULL DEFAULT now(),
    updated_at timestamp with time zone NOT NULL DEFAULT now(),
    last_accessed_at timestamp with time zone,
    ended_at timestamp with time zone,
    CONSTRAINT sessions_pkey PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS public.spec_workflows
(
    id bigserial NOT NULL,
    tracking_id text COLLATE pg_catalog."default" NOT NULL,
    feature_slug text COLLATE pg_catalog."default" NOT NULL,
    feature_number text COLLATE pg_catalog."default" NOT NULL,
    current_phase text COLLATE pg_catalog."default" NOT NULL,
    status text COLLATE pg_catalog."default" NOT NULL,
    gates jsonb NOT NULL DEFAULT '{}'::jsonb,
    created_at timestamp with time zone NOT NULL DEFAULT now(),
    updated_at timestamp with time zone NOT NULL DEFAULT now(),
    CONSTRAINT spec_workflows_pkey PRIMARY KEY (id),
    CONSTRAINT spec_workflows_tracking_id_feature_number_key UNIQUE (tracking_id, feature_number)
);

CREATE TABLE IF NOT EXISTS public.sync_logs
(
    id bigserial NOT NULL,
    workspace_id bigint NOT NULL,
    user_id integer,
    client_id character varying(128) COLLATE pg_catalog."default" NOT NULL,
    batch_id character varying(128) COLLATE pg_catalog."default" NOT NULL,
    idempotency_key character varying(300) COLLATE pg_catalog."default" NOT NULL,
    operation_count integer NOT NULL DEFAULT 0,
    status character varying(20) COLLATE pg_catalog."default" NOT NULL,
    conflict_count integer NOT NULL DEFAULT 0,
    request_hash character varying(64) COLLATE pg_catalog."default",
    details jsonb NOT NULL DEFAULT '{}'::jsonb,
    created_at timestamp with time zone NOT NULL DEFAULT now(),
    CONSTRAINT sync_logs_pkey PRIMARY KEY (id),
    CONSTRAINT uq_sync_logs_batch UNIQUE (workspace_id, client_id, batch_id)
);

CREATE TABLE IF NOT EXISTS public.token_usage
(
    id bigserial NOT NULL,
    tracking_id text COLLATE pg_catalog."default" NOT NULL,
    model text COLLATE pg_catalog."default",
    prompt_tokens integer NOT NULL DEFAULT 0,
    completion_tokens integer NOT NULL DEFAULT 0,
    total_tokens integer NOT NULL DEFAULT 0,
    created_at timestamp with time zone NOT NULL DEFAULT now(),
    CONSTRAINT token_usage_pkey PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS public.users
(
    id serial NOT NULL,
    email character varying(255) COLLATE pg_catalog."default" NOT NULL,
    username character varying(100) COLLATE pg_catalog."default" NOT NULL,
    full_name character varying(255) COLLATE pg_catalog."default",
    password_hash character varying(255) COLLATE pg_catalog."default" NOT NULL,
    role character varying(50) COLLATE pg_catalog."default" NOT NULL DEFAULT 'user'::character varying,
    is_active boolean NOT NULL DEFAULT true,
    last_login timestamp with time zone,
    login_count integer NOT NULL DEFAULT 0,
    created_at timestamp with time zone NOT NULL DEFAULT now(),
    updated_at timestamp with time zone NOT NULL DEFAULT now(),
    CONSTRAINT users_pkey PRIMARY KEY (id),
    CONSTRAINT users_email_key UNIQUE (email),
    CONSTRAINT users_username_key UNIQUE (username)
);

CREATE TABLE IF NOT EXISTS public.workspace_audit_logs
(
    id bigserial NOT NULL,
    workspace_id bigint,
    user_id integer,
    event_type character varying(100) COLLATE pg_catalog."default" NOT NULL,
    entity_type character varying(50) COLLATE pg_catalog."default",
    entity_path text COLLATE pg_catalog."default",
    details jsonb NOT NULL DEFAULT '{}'::jsonb,
    correlation_id character varying(128) COLLATE pg_catalog."default",
    created_at timestamp with time zone NOT NULL DEFAULT now(),
    CONSTRAINT workspace_audit_logs_pkey PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS public.workspaces
(
    id bigserial NOT NULL,
    tracking_id text COLLATE pg_catalog."default" NOT NULL DEFAULT (gen_random_uuid())::text,
    owner_user_id integer,
    name character varying(255) COLLATE pg_catalog."default" NOT NULL DEFAULT ''::character varying,
    description text COLLATE pg_catalog."default",
    local_fs_path text COLLATE pg_catalog."default",
    status character varying(20) COLLATE pg_catalog."default" NOT NULL DEFAULT 'active'::character varying,
    sync_version integer NOT NULL DEFAULT 1,
    version integer NOT NULL DEFAULT 1,
    active_session_id bigint,
    created_at timestamp with time zone NOT NULL DEFAULT now(),
    updated_at timestamp with time zone NOT NULL DEFAULT now(),
    last_accessed_at timestamp with time zone,
    deleted_at timestamp with time zone,
    CONSTRAINT workspaces_pkey PRIMARY KEY (id),
    CONSTRAINT workspaces_tracking_id_key UNIQUE (tracking_id)
);

ALTER TABLE IF EXISTS public.agent_checkpoints
    ADD CONSTRAINT agent_checkpoints_tracking_id_fkey FOREIGN KEY (tracking_id)
    REFERENCES public.workspaces (tracking_id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE CASCADE;


ALTER TABLE IF EXISTS public.agent_messages
    ADD CONSTRAINT agent_messages_tracking_id_fkey FOREIGN KEY (tracking_id)
    REFERENCES public.workspaces (tracking_id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE CASCADE;


ALTER TABLE IF EXISTS public.agent_session_snapshots
    ADD CONSTRAINT agent_session_snapshots_tracking_id_fkey FOREIGN KEY (tracking_id)
    REFERENCES public.workspaces (tracking_id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE CASCADE;


ALTER TABLE IF EXISTS public.chat_messages
    ADD CONSTRAINT chat_messages_session_id_fkey FOREIGN KEY (session_id)
    REFERENCES public.sessions (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE CASCADE;
CREATE INDEX IF NOT EXISTS idx_chat_messages_session
    ON public.chat_messages(session_id);


ALTER TABLE IF EXISTS public.chat_messages
    ADD CONSTRAINT chat_messages_workspace_id_fkey FOREIGN KEY (workspace_id)
    REFERENCES public.workspaces (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE CASCADE;
CREATE INDEX IF NOT EXISTS idx_chat_messages_workspace
    ON public.chat_messages(workspace_id);


ALTER TABLE IF EXISTS public.connectors
    ADD CONSTRAINT connectors_workspace_id_fkey FOREIGN KEY (workspace_id)
    REFERENCES public.workspaces (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE CASCADE;
CREATE INDEX IF NOT EXISTS idx_connectors_workspace
    ON public.connectors(workspace_id);


ALTER TABLE IF EXISTS public.long_term_memory
    ADD CONSTRAINT long_term_memory_tracking_id_fkey FOREIGN KEY (tracking_id)
    REFERENCES public.workspaces (tracking_id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE CASCADE;


ALTER TABLE IF EXISTS public.run_states
    ADD CONSTRAINT run_states_tracking_id_fkey FOREIGN KEY (tracking_id)
    REFERENCES public.workspaces (tracking_id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE CASCADE;
CREATE INDEX IF NOT EXISTS run_states_pkey
    ON public.run_states(tracking_id);


ALTER TABLE IF EXISTS public.session_state
    ADD CONSTRAINT session_state_session_id_fkey FOREIGN KEY (session_id)
    REFERENCES public.sessions (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE SET NULL;
CREATE INDEX IF NOT EXISTS idx_session_state_session
    ON public.session_state(session_id);


ALTER TABLE IF EXISTS public.session_state
    ADD CONSTRAINT session_state_workspace_id_fkey FOREIGN KEY (workspace_id)
    REFERENCES public.workspaces (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE CASCADE;
CREATE INDEX IF NOT EXISTS uq_session_state_workspace
    ON public.session_state(workspace_id);


ALTER TABLE IF EXISTS public.sessions
    ADD CONSTRAINT sessions_user_id_fkey FOREIGN KEY (user_id)
    REFERENCES public.users (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE CASCADE;
CREATE INDEX IF NOT EXISTS idx_sessions_user
    ON public.sessions(user_id);


ALTER TABLE IF EXISTS public.sessions
    ADD CONSTRAINT sessions_workspace_id_fkey FOREIGN KEY (workspace_id)
    REFERENCES public.workspaces (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE CASCADE;
CREATE INDEX IF NOT EXISTS idx_sessions_workspace
    ON public.sessions(workspace_id);


ALTER TABLE IF EXISTS public.spec_workflows
    ADD CONSTRAINT spec_workflows_tracking_id_fkey FOREIGN KEY (tracking_id)
    REFERENCES public.workspaces (tracking_id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE CASCADE;


ALTER TABLE IF EXISTS public.sync_logs
    ADD CONSTRAINT sync_logs_user_id_fkey FOREIGN KEY (user_id)
    REFERENCES public.users (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE SET NULL;


ALTER TABLE IF EXISTS public.sync_logs
    ADD CONSTRAINT sync_logs_workspace_id_fkey FOREIGN KEY (workspace_id)
    REFERENCES public.workspaces (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE CASCADE;
CREATE INDEX IF NOT EXISTS idx_sync_logs_workspace
    ON public.sync_logs(workspace_id);


ALTER TABLE IF EXISTS public.token_usage
    ADD CONSTRAINT token_usage_tracking_id_fkey FOREIGN KEY (tracking_id)
    REFERENCES public.workspaces (tracking_id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE CASCADE;


ALTER TABLE IF EXISTS public.workspace_audit_logs
    ADD CONSTRAINT workspace_audit_logs_user_id_fkey FOREIGN KEY (user_id)
    REFERENCES public.users (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE SET NULL;
CREATE INDEX IF NOT EXISTS idx_workspace_audit_user
    ON public.workspace_audit_logs(user_id);


ALTER TABLE IF EXISTS public.workspace_audit_logs
    ADD CONSTRAINT workspace_audit_logs_workspace_id_fkey FOREIGN KEY (workspace_id)
    REFERENCES public.workspaces (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE CASCADE;
CREATE INDEX IF NOT EXISTS idx_workspace_audit_workspace
    ON public.workspace_audit_logs(workspace_id);


ALTER TABLE IF EXISTS public.workspaces
    ADD CONSTRAINT workspaces_active_session_id_fkey FOREIGN KEY (active_session_id)
    REFERENCES public.sessions (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE SET NULL;


ALTER TABLE IF EXISTS public.workspaces
    ADD CONSTRAINT workspaces_owner_user_id_fkey FOREIGN KEY (owner_user_id)
    REFERENCES public.users (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE CASCADE;

END;