"""
Custom agent registry — file-convention discovery (BMAD / Claude Code model).

Agents and skills are FILES in the user's workspace, not database rows.
Anything that follows the convention appears automatically — whether it was
generated by our agent-builder workflow, hand-written, or copied in from an
existing BMAD / Claude Code / Spec Kit install. There is no registration step.

THE FOLDER DECIDES WHAT A FILE IS. Agents live under an `agents/` folder,
skills under a `skills/` folder, and everything below one belongs to it at any
depth:

    agents/mary.md                        an agent
    agents/priya/AGENT.md                 an agent
    agents/priya/anything.md              an agent
    skills/java-python/SKILL.md           a skill
    skills/java-python/templates/x.md     that skill's TEMPLATE
    skills/java-python/checklists/gate.md that skill's CHECKLIST

The nearest declaring ancestor wins, which is what keeps a checklist inside a
skill from registering as another skill. A file with no such ancestor is not a
definition, wherever it sits and whatever its frontmatter says — so "agents
live under agents/" is a rule you can check by looking at the tree, and a
stray note can never become an agent by accident.

Nesting an artifact under the skill it serves is the point, not decoration:
opening one folder shows the method, its gates and its templates together,
so a workspace with a dozen agents stays legible.

An unambiguous filename still works anywhere — SKILL.md, SKILLS.md, AGENT.md,
AGENTS.md, *.agent.md, *.chatmode.md — because those name themselves.

Framework roots scanned (first definition of a name wins, in this order):

    .devaccel/**           ours — agents, skills, and their artifacts
    .claude/**             Claude Code subagents + skills
    .agents/**             BMAD v6 canonical skills root (cross-tool)
    .github/**             Copilot agent stubs, chatmodes
    _bmad|bmad|.bmad-core  BMAD installs (v4 yaml-block and v6 layouts)
    <any dir containing a matching file>

BMAD v6 "skills architecture": the canonical content of BOTH agents and
skills lives in skill folders (SKILL.md with name/description frontmatter);
per-IDE agent files are thin STUBS — .github/agents/<name>.agent.md has
`description:`-only frontmatter and a body that says to load
{project-root}/.agents/skills/<name>/SKILL.md. This registry resolves a
stub to its skill folder (matched by name across all skill roots) and uses
the SKILL.md as the agent's definition. Skill folders named `bmad-agent-*`
are agent personas even without a stub (Claude-Code-only installs). A
skill folder claimed as an agent is NOT also listed as a plain skill.

Agent files use Claude Code-compatible frontmatter (name, description,
tools, skills, model, plus the optional persona identity fields) with the
body as the system prompt — see spec_driven/parsers.py. `skills:` names
skill folders whose SKILL.md is injected alongside the agent when it runs
(the BMAD agent↔skill link).

Security: agent files are UNTRUSTED input. Reads are size-capped and names are
sanitized for display. The tool list is persona guidance only; it never changes
the request's permission policy. The caller's permission_mode plus explicit
allow/deny rules remain the sole tool-access controls.

Pattern C note: when the workspace lives on the CLIENT machine this module
sees nothing — the client scans the same conventions itself and sends the
catalog metadata with the request (skill_catalog), then serves individual
bodies through the client-delegated `skill` tool.
"""

import os
from pathlib import Path
from typing import Dict, List, Optional

from spec_driven.parsers import (
    _persona_for,
    parse_agents,
    parse_bmad_agent,
    parse_frontmatter,
    parse_skill,
    parse_skills_file as _parse_stacked_skills,
)
from utils.logger import get_logger

log = get_logger(__name__)

# Directories that anchor a framework. The walk starts here rather than at the
# workspace root so a large repo doesn't pay for a full tree crawl on every
# request; `_discover_extra_roots` adds any other directory that turns out to
# hold matching files.
_FRAMEWORK_ROOTS = [
    ".devaccel", ".claude", ".agents", ".github",
    "_bmad", "bmad", ".bmad-core",
]
# Exclusion, not inclusion — the repo's standing rule for scanning untrusted
# trees. Anything not listed here is fair game.
_SKIP_DIRS = {
    "node_modules", ".git", ".venv", "venv", "env", "__pycache__",
    "dist", "build", "out", ".next", ".nuxt", ".cache", ".pytest_cache",
    "target", "vendor", "coverage", ".tox", ".mypy_cache",
    # Our own per-thread scratch area: .devaccel/<thread>/tmp|input|output
    # holds run artifacts, not definitions, and can hold thousands of files.
    "tmp", "input", "output",
}
# Basenames that ARE a definition, whatever folder they sit in.
_SKILL_BASENAMES = {"skill.md", "skills.md"}
_AGENT_BASENAMES = {"agent.md", "agents.md"}
_AGENT_SUFFIXES = (".agent.md", ".chatmode.md")
# THE FOLDER DECIDES. `agents/` holds agents, `skills/` holds skills, and
# everything below one of them belongs to it however deeply it is nested:
#
#     agents/mary.md                     an agent
#     agents/priya/AGENT.md              an agent
#     agents/priya/anything.md           an agent
#     skills/java-python/SKILL.md        a skill
#     skills/java-python/checklists/x.md a CHECKLIST — the nearer folder wins
#
# A file with no such ancestor is not a definition, wherever it sits. That is
# the rule an organisation can actually hold people to: "agents live under
# agents/" is checkable by looking, and it means a stray note in the repo can
# never become an agent by accident.
_AGENT_DIR_NAMES = {"agent", "agents", "chatmode", "chatmodes",
                    "persona", "personas"}
_SKILL_DIR_NAMES = {"skill", "skills"}
_DEFINITION_DIR_NAMES = _AGENT_DIR_NAMES | _SKILL_DIR_NAMES

# Folders that hold an agent's or skill's SUPPORTING material rather than more
# definitions. Nested inside `skills/<name>/`, they are what makes one folder
# tell the whole story: open it and the method, its gates and its templates
# are all there together. The nearest of these ancestors names the kind, so
# `skills/x/checklists/gate.md` is a checklist, not a second skill.
_ARTIFACT_DIR_KINDS = {
    "template": "template", "templates": "template",
    "checklist": "checklist", "checklists": "checklist",
    "task": "task", "tasks": "task",
    "workflow": "workflow", "workflows": "workflow",
    "data": "data",
    "reference": "reference", "references": "reference",
}

# Documentation that lives beside definitions and is not one.
_DOC_BASENAMES = {"readme.md", "changelog.md", "license.md", "contributing.md",
                  "index.md", "todo.md", "notes.md"}

# Bounds. A framework is hundreds of small files; anything past these is a
# misconfigured root (someone pointed us at node_modules), so we stop rather
# than stall the request that triggered the scan.
_MAX_DEPTH = 8
_MAX_CANDIDATES = 2_000
_MAX_FILE_BYTES = 128 * 1024      # ignore anything bigger — not a prompt file

# One agent per file — ours first, then Claude Code, then BMAD installs
# (.bmad-core = classic v4 layout: Markdown + embedded yaml block). These
# globs are the FAST PATH: they cost one glob each and cover every layout we
# already knew about. The shape walk below catches everything else.
_AGENT_FILE_GLOBS = [
    ".devaccel/agents/*.md",
    ".claude/agents/*.md",
    ".bmad-core/agents/*.md",
    "_bmad/*/agents/*.md",
    "bmad/*/agents/*.md",
]
# GitHub Copilot agent stubs (BMAD v6): name = filename minus ".agent.md",
# frontmatter has only description:, body points at the canonical SKILL.md.
_AGENT_STUB_GLOB = ".github/agents/*.agent.md"
# Stacked rosters (legacy layout + gate-1 proposals) — parsed last so a
# dedicated per-file definition of the same name wins.
_ROSTER_FILE_GLOBS = [
    ".devaccel/agents/*/agents.md",
    ".devaccel/agents/agents.md",
]
_SKILL_FILE_GLOBS = [
    ".agents/skills/*/SKILL.md",     # BMAD v6 canonical skills root
    ".devaccel/skills/*/SKILL.md",
    ".claude/skills/*/SKILL.md",
]
# BMAD v6 agent personas live AS skills with this folder-name prefix
# (e.g. .claude/skills/bmad-agent-dev/SKILL.md) — surfaced as agents even
# when no .github stub exists (Claude-Code-only installs).
_BMAD_AGENT_SKILL_PREFIX = "bmad-agent-"
# Reserved basenames in agents/ that are NOT single-agent files.
#
# `skills.md` is deliberately NOT here: a framework that keeps its skills in
# one stacked file is as valid as one that keeps them in folders, and
# excluding it made those installs invisible.
_NON_AGENT_BASENAMES = {"agents.md", "roster.md", "readme.md"}

# Caps for the injected persona context (chars ≈ tokens*4).
_SKILL_INJECT_CAP = 6_000
_CONTEXT_TOTAL_CAP = 24_000


def _read_capped(path: Path) -> Optional[str]:
    try:
        if not path.is_file() or path.stat().st_size > _MAX_FILE_BYTES:
            return None
        return path.read_text(encoding="utf-8", errors="replace")
    except OSError:
        return None


def _rel(path: Path, root: Path) -> str:
    try:
        return path.relative_to(root).as_posix()
    except ValueError:
        return path.as_posix()


def _classify(basename: str, ancestors: tuple = ()) -> Optional[str]:
    """What a file IS: 'agent' | 'skill' | an artifact kind, or None.

    `ancestors` is the chain of directory names above the file, NEAREST FIRST.

    Two rules, in order:
      1. an unambiguous filename — SKILL.md, AGENT.md, *.agent.md — says it
         outright, wherever the file sits;
      2. otherwise the NEAREST declaring ancestor decides. Nearest matters:
         `skills/java-python/checklists/gate.md` is a checklist that belongs
         to that skill, not a second skill, and reading the chain outward
         from the file is what gets that right.

    No declaring ancestor means it is not a definition. A note in `docs/` or
    a stray markdown file in the repo cannot become an agent by accident,
    which is what makes "agents live under agents/" a rule you can hold
    people to.
    """
    lower = basename.lower()
    if lower in _SKILL_BASENAMES:
        return "skill"
    if lower in _AGENT_BASENAMES or lower.endswith(_AGENT_SUFFIXES):
        return "agent"
    if not lower.endswith(".md") or lower in _DOC_BASENAMES:
        return None
    for folder in ancestors:
        name = folder.lower()
        if name in _ARTIFACT_DIR_KINDS:
            return _ARTIFACT_DIR_KINDS[name]
        if name in _AGENT_DIR_NAMES:
            return "agent"
        if name in _SKILL_DIR_NAMES:
            return "skill"
    return None


def walk_definitions(workspace: str) -> Dict[str, List[Path]]:
    """Every definition file under the workspace's framework roots, keyed
    'skill' / 'agent'.

    The rule is the basename, not the path: `.devaccel/SKILL.md`,
    `.devaccel/migration/SKILL.md` and `.devaccel/packs/acme/skills/x/SKILL.md`
    all qualify, so an imported framework works whatever shape it ships in.

    Roots are the known framework directories plus any top-level directory
    that turns out to contain a definition — that second clause is what makes
    an invented layout like `frameworks/acme-sdlc/roles/*.agent.md` register
    without being named anywhere in this file.
    """
    root = Path(workspace)
    found: Dict[str, List[Path]] = {"skill": [], "agent": []}
    if not root.is_dir():
        return found

    roots = [root / name for name in _FRAMEWORK_ROOTS]
    roots += _discover_extra_roots(root)

    budget = _MAX_CANDIDATES
    seen: set = set()
    for start in roots:
        if not start.is_dir() or start in seen:
            continue
        seen.add(start)
        base_depth = len(start.parts)
        for dirpath, dirnames, filenames in os.walk(start):
            here = Path(dirpath)
            if len(here.parts) - base_depth >= _MAX_DEPTH:
                dirnames[:] = []
                continue
            # Prune in place — os.walk honours mutation of dirnames, so
            # excluded trees are never even stat-ed.
            dirnames[:] = [d for d in dirnames if d not in _SKIP_DIRS]
            try:
                ancestors = tuple(reversed(here.relative_to(root).parts))
            except ValueError:
                ancestors = (here.name,)
            for filename in filenames:
                kind = _classify(filename, ancestors)
                if kind is None:
                    continue
                # Artifacts (templates, checklists, …) are discovered for the
                # catalog through the skill folder that contains them; they
                # are not agents or skills themselves, so nothing here claims
                # them as one.
                found.setdefault(kind, []).append(here / filename)
                budget -= 1
                if budget <= 0:
                    log.warning(
                        f"Skill discovery hit the {_MAX_CANDIDATES}-file cap "
                        f"under {_rel(start, root)} — later files ignored"
                    )
                    return found
    return found


def _discover_extra_roots(root: Path) -> List[Path]:
    """Top-level directories holding a definition somewhere inside them.

    This is what makes the top-level folder name irrelevant: a framework
    unpacked as `myframework/agent/mary.md` or `sdlc-pack/skills/x/SKILL.md`
    registers exactly like one that used `.devaccel`.

    One shallow probe per directory (depth 3) so an arbitrary framework drop
    is found without crawling the whole repository. A project that keeps its
    definitions deeper than that still works through a named root.
    """
    extra: List[Path] = []
    try:
        entries = sorted(p for p in root.iterdir() if p.is_dir())
    except OSError:
        return extra
    for entry in entries:
        if entry.name in _SKIP_DIRS or entry.name in _FRAMEWORK_ROOTS:
            continue
        for pattern in ("*", "*/*", "*/*/*"):
            try:
                if any(_classify(p.name, tuple(reversed(
                            p.parent.relative_to(entry).parts)) + (entry.name,))
                       in ("skill", "agent")
                       for p in entry.glob(pattern) if p.is_file()):
                    extra.append(entry)
                    break
            except (OSError, ValueError):
                break
    return extra


def scan_custom_agents(workspace: str) -> Dict[str, List[Dict]]:
    """Scan `workspace` for agent/skill definition files.

    Returns {"agents": [...], "skills": [...]} where each agent dict is the
    parse_agents() shape plus `source` (workspace-relative path) and
    `resolved_skills` (the subset of its `skills:` names that actually exist
    as skill folders). Unreadable/oversized files are skipped silently —
    discovery must never break the request that triggered it.
    """
    root = Path(workspace)
    agents: Dict[str, Dict] = {}     # name → agent (first definition wins)
    skills: Dict[str, Dict] = {}
    skill_bodies: Dict[str, str] = {}  # skill name → raw SKILL.md content

    if not root.is_dir():
        return {"agents": [], "skills": [], "artifacts": []}

    # Fast path first, so the canonical roots win name collisions, then the
    # shape walk adds every SKILL.md/SKILLS.md the globs couldn't express.
    walked = walk_definitions(workspace)
    skill_paths = [p for glob in _SKILL_FILE_GLOBS for p in sorted(root.glob(glob))]
    skill_paths += sorted(walked["skill"])

    for path in skill_paths:
        content = _read_capped(path)
        if content is None:
            continue
        # A stacked skills.md holds SEVERAL definitions; a SKILL.md holds one
        # and may legitimately have no frontmatter at all (the whole file is
        # then the instruction). parse_skill covers the second case, so only
        # the stacked form needs the multi-block path.
        #
        # The fallback name follows the convention in play. SKILL.md is named
        # by its FOLDER (skills/<name>/SKILL.md) and may carry no frontmatter
        # at all — the whole file is then the instruction, which BMAD allows.
        #
        # A file identified only by its FOLDER (skills/expand.md) gets NO
        # fallback: it must declare a name. Without that rule a stray
        # `docs/skills/notes.md` would register itself as a skill called
        # "notes", and a documentation folder would quietly become a
        # framework.
        if path.name.lower() == "skills.md":
            parsed = _parse_stacked_skills(content)
        elif path.name.lower() in _SKILL_BASENAMES:
            parsed = [parse_skill(content, fallback_name=path.parent.name)]
        else:
            parsed = [parse_skill(content, fallback_name="")]
        for skill in parsed:
            if not skill or not skill.get("name") or skill["name"] in skills:
                continue
            skill["source"] = _rel(path, root)
            skills[skill["name"]] = skill
            skill_bodies[skill["name"]] = content

    def _add_agents_from(path: Path):
        content = _read_capped(path)
        if content is None:
            return
        parsed = parse_agents(content)
        if not parsed:
            # .bmad-core-style agent: Markdown + embedded ```yaml block
            # (agent: {id, title, whenToUse, …}) instead of frontmatter.
            bmad = parse_bmad_agent(content, fallback_name=path.stem)
            parsed = [bmad] if bmad else []
        for agent in parsed:
            if agent["name"] in agents:
                continue
            agent["source"] = _rel(path, root)
            agent["resolved_skills"] = [s for s in agent["skills"] if s in skills]
            agents[agent["name"]] = agent

    def _add_agent_from_skill(name: str, source: str,
                              stub_meta: Dict = None, stub_body: str = ""):
        """BMAD v6: the agent's canonical definition IS a skill folder.
        Without one, the .agent.md file itself is the definition — that is
        GitHub Copilot's own custom-agent format (agent profile: frontmatter
        + prompt body), so a full-content Copilot agent works too."""
        if name in agents:
            return
        body = skill_bodies.get(name)
        parsed = parse_agents(body)[:1] if body else []
        if parsed:
            agent = parsed[0]
            agent["name"] = name  # stub filename wins over frontmatter drift
        else:
            meta = stub_meta or {}
            _csv = lambda v: [t.strip() for t in (v or "").split(",") if t.strip()]
            agent = {
                "name": name,
                "description": meta.get("description", ""),
                "tools": _csv(meta.get("tools")),
                "skills": _csv(meta.get("skills")),
                "tasks": [],
                "model": meta.get("model", ""),
                # A stub's frontmatter carries description ONLY, so the
                # persona has to come out of that sentence ("…asks to talk to
                # Mary"). Without this every agent in a stock BMAD install is
                # nameless.
                "persona": _persona_for(meta, stub_body),
                "title": meta.get("title", ""),
                "role": meta.get("role", ""),
                "icon": meta.get("icon", ""),
                "when_to_use": meta.get("whentouse", "") or meta.get("when_to_use", ""),
                "system_prompt": stub_body,
            }
        agent["source"] = source
        agent["resolved_skills"] = [s for s in agent["skills"] if s in skills]
        agents[name] = agent
        # An agent persona is not ALSO a plain skill.
        skills.pop(name, None)

    for glob in _AGENT_FILE_GLOBS:
        for path in sorted(root.glob(glob)):
            if path.name.lower() in _NON_AGENT_BASENAMES:
                continue
            _add_agents_from(path)

    # GitHub Copilot agents: BMAD stubs resolve to their canonical SKILL.md
    # by name; full-content agent profiles stand on their own body. The
    # canonical .github/agents/ glob runs first so it wins the name, then
    # the walk contributes the same shape found anywhere else.
    stub_paths = sorted(root.glob(_AGENT_STUB_GLOB))
    stub_paths += [p for p in sorted(walked["agent"])
                   if p.name.lower().endswith(_AGENT_SUFFIXES)]
    for path in stub_paths:
        # A stub is named by its FILE (bmad-agent-dev.agent.md), but a
        # principal file is named by its FOLDER: agents/priya/AGENT.md is
        # Priya's agent, not one called "AGENT".
        name = (path.parent.name if path.name.lower() in _AGENT_BASENAMES
                else path.name.rsplit(".", 2)[0])
        content = _read_capped(path)
        if not name or content is None:
            continue
        block = parse_frontmatter(content)
        _add_agent_from_skill(name, _rel(path, root),
                              stub_meta=block[0] if block else None,
                              stub_body=block[1] if block else content.strip())

    # Everything else the walk classified as an agent: a `.md` inside a folder
    # named agent/ agents/ personas/ … at any depth, under any top-level name.
    # This is the `myframework/agent/mary.md` case — the folder said what it
    # holds, so the file is read as an agent without needing a filename
    # convention on top.
    for path in sorted(walked["agent"]):
        if path.name.lower().endswith(_AGENT_SUFFIXES):
            continue                      # already handled as a stub above
        if path.name.lower() in _NON_AGENT_BASENAMES - _AGENT_BASENAMES:
            continue                      # roster.md / readme.md
        before = len(agents)
        _add_agents_from(path)
        if len(agents) > before:
            continue
        # Nothing parsed — the file declares no `name:`, which is the BMAD
        # stub shape. Fall back to naming it after its FOLDER for a principal
        # file (agents/priya/AGENT.md is Priya's agent, not one called
        # "AGENT") and after the file otherwise.
        content = _read_capped(path)
        if content is None:
            continue
        name = (path.parent.name if path.name.lower() in _AGENT_BASENAMES
                else path.stem)
        block = parse_frontmatter(content)
        if not name or block is None:
            continue          # no frontmatter at all — documentation
        _add_agent_from_skill(name, _rel(path, root),
                              stub_meta=block[0], stub_body=block[1])

    # BMAD agent personas that exist only as skills (no stub).
    for name in [n for n in list(skills) if n.startswith(_BMAD_AGENT_SKILL_PREFIX)]:
        _add_agent_from_skill(name, skills[name]["source"])

    for glob in _ROSTER_FILE_GLOBS:
        for path in sorted(root.glob(glob)):
            _add_agents_from(path)

    # NOTE: there is deliberately no catch-all pass over loose .md files.
    # A definition is identified by the folder it lives under, so a file
    # outside agents/ or skills/ is not one however its frontmatter reads.
    # That is what makes "agents live under agents/" enforceable by
    # looking at the tree rather than by reading every file in the repo.

    # Supporting material — the templates, checklists and tasks nested inside
    # a skill or agent folder. Surfaced so the model can see that a gate or a
    # template exists without opening the folder; `build_catalog` attributes
    # each one to the definition it sits under.
    artifacts: List[Dict] = []
    for kind, paths in walked.items():
        if kind in ("agent", "skill"):
            continue
        for path in sorted(paths):
            content = _read_capped(path)
            if content is None:
                continue
            parsed = parse_skill(content, fallback_name=path.stem)
            if not parsed or not parsed.get("name"):
                continue
            parsed["kind"] = kind        # the FOLDER names the kind
            parsed["source"] = _rel(path, root)
            artifacts.append(parsed)

    return {"agents": list(agents.values()), "skills": list(skills.values()),
            "artifacts": artifacts}


def find_agent(workspace: str, name: str) -> Optional[Dict]:
    """The named agent from a fresh scan, or None."""
    for agent in scan_custom_agents(workspace)["agents"]:
        if agent["name"] == name:
            return agent
    return None


def build_agent_context(agent: Dict, skill_contents: Dict[str, str]) -> str:
    """The persona block injected in front of the run's memory context when a
    custom agent is selected: identity + system prompt + its skills' content.
    `skill_contents` maps skill name → SKILL.md content (server-scanned or
    client-sent); only skills the agent declares are injected, size-capped.
    """
    parts = [
        f"## Active Custom Agent: {agent['name']}",
        f"{agent['description']}",
        "You are acting as this agent for the entire turn. Follow its "
        "instructions and stay within its role.",
    ]
    if agent.get("system_prompt"):
        parts.append(agent["system_prompt"])
    if agent.get("tools"):
        # Advisory, not enforced — steers the model toward the role's
        # toolset while every tool stays available for what the task needs.
        parts.append("Preferred tools for this role: "
                     + ", ".join(agent["tools"])
                     + ". Use others when the task requires them.")
    for skill_name in agent.get("skills", []):
        content = (skill_contents.get(skill_name) or "").strip()
        if not content:
            continue
        parts.append(f"### Skill: {skill_name}\n{content[:_SKILL_INJECT_CAP]}")
    return "\n\n".join(parts)[:_CONTEXT_TOTAL_CAP]
