"""AppDBProtocol — the ONLY interface callers use.

Every method returns a dataclass (or a list of dataclasses) from `models.py`.
Backends (`SqliteAppDB`, later `PostgresAppDB`) implement this Protocol.
"""
from __future__ import annotations

from typing import Optional, Protocol, runtime_checkable

from .models import (
    Artefact,
    Attachment,
    Credential,
    IndexedSource,
    Message,
    Org,
    Project,
    Thread,
    User,
    VectorChunk,
)


@runtime_checkable
class AppDBProtocol(Protocol):
    """Data access facade for all operational (non-vector) state."""

    # ---- lifecycle --------------------------------------------------------
    def close(self) -> None: ...
    def ping(self) -> bool: ...

    # ---- orgs / users -----------------------------------------------------
    def get_default_org(self) -> Org: ...
    def get_default_user(self) -> User: ...

    def get_org(self, org_id: str) -> Optional[Org]: ...
    def get_user(self, user_id: str) -> Optional[User]: ...

    # ---- credentials (Jira / Confluence / ...) ----------------------------
    def upsert_credential(self, cred: Credential) -> Credential: ...
    def get_credential(
        self, user_id: str, provider: str, base_url: Optional[str] = None
    ) -> Optional[Credential]: ...
    def list_credentials(self, user_id: str) -> list[Credential]: ...
    def delete_credential(self, credential_id: str) -> bool: ...

    # ---- projects ---------------------------------------------------------
    def get_default_project(self) -> Project: ...
    def create_project(self, project: Project) -> Project: ...
    def get_project(self, project_id: str) -> Optional[Project]: ...
    def list_projects(self, org_id: str) -> list[Project]: ...
    def delete_project(self, project_id: str) -> bool: ...

    # ---- threads / messages ----------------------------------------------
    def upsert_thread(self, thread: Thread) -> Thread: ...
    def get_thread(self, thread_id: str) -> Optional[Thread]: ...
    def list_threads(self, user_id: str, limit: int = 50) -> list[Thread]: ...

    def add_message(self, msg: Message) -> Message: ...
    def get_messages(self, thread_id: str) -> list[Message]: ...

    # ---- attachments ------------------------------------------------------
    def upsert_attachment(self, att: Attachment) -> Attachment: ...
    def get_attachment(self, attachment_id: str) -> Optional[Attachment]: ...
    def get_attachment_by_fingerprint(
        self, org_id: str, fingerprint: str
    ) -> Optional[Attachment]: ...
    def list_attachments(
        self, org_id: str, thread_id: Optional[str] = None
    ) -> list[Attachment]: ...
    def mark_attachment_indexed(self, attachment_id: str, indexed: bool) -> None: ...

    # ---- artefacts (agent outputs) ---------------------------------------
    def add_artefact(self, art: Artefact) -> Artefact: ...
    def list_artefacts(self, thread_id: str) -> list[Artefact]: ...
    def approve_artefact(self, artefact_id: str, approver: str) -> Optional[Artefact]: ...

    # ---- vector-chunk metadata (companion to FAISS/pgvector) --------------
    def add_vector_chunks(self, chunks: list[VectorChunk]) -> list[int]: ...
    def get_vector_chunks_by_ids(self, ids: list[int]) -> list[VectorChunk]: ...
    def delete_vector_chunks_by_source(self, source: str, org_id: str) -> int: ...
    def list_chunk_ids(
        self,
        org_id: Optional[str] = None,
        project_id: Optional[str] = None,
    ) -> list[int]: ...

    # ---- indexed-source fingerprints -------------------------------------
    def get_indexed_source(
        self, source: str, org_id: str
    ) -> Optional[IndexedSource]: ...
    def upsert_indexed_source(self, src: IndexedSource) -> IndexedSource: ...
    def delete_indexed_source(self, source: str, org_id: str) -> bool: ...
    def list_indexed_sources(
        self, org_id: str, project_id: Optional[str] = None
    ) -> list[IndexedSource]: ...
