"""Repository protocol for Workspace Studio services."""

from __future__ import annotations

from typing import Any, Protocol

from workspace_studio.models.domain import SessionRecord, WorkspaceRecord


class WorkspaceRepository(Protocol):
    def health(self) -> bool: ...
    def create_workspace(self, owner_user_id: int, name: str, description: str | None, local_fs_path: str | None) -> WorkspaceRecord: ...
    # owner_user_id=None lists across all owners (admins only — the service
    # decides; repositories never make authorisation decisions).
    def list_workspaces(self, owner_user_id: int | None, page: int, page_size: int, status: str | None) -> tuple[list[WorkspaceRecord], int]: ...
    def get_workspace(self, workspace_id: int) -> WorkspaceRecord | None: ...
    def update_workspace(self, workspace_id: int, updates: dict[str, Any], expected_version: int | None) -> WorkspaceRecord | None: ...
    def set_workspace_status(self, workspace_id: int, status: str) -> WorkspaceRecord | None: ...
    def set_active_workspace(self, workspace_id: int, session_id: int | None) -> WorkspaceRecord | None: ...

    def create_session(self, workspace_id: int, user_id: int, session_name: str, context_snapshot: dict[str, Any], is_active: bool) -> SessionRecord: ...
    def list_sessions(self, workspace_id: int, page: int, page_size: int) -> tuple[list[SessionRecord], int]: ...
    def get_active_session(self, workspace_id: int) -> SessionRecord | None: ...
    def update_session(self, workspace_id: int, session_id: int, updates: dict[str, Any]) -> SessionRecord | None: ...

    def get_recovery_state(self, workspace_id: int) -> dict[str, Any] | None: ...
    def save_recovery_state(self, workspace_id: int, session_id: int | None, state: dict[str, Any], expected_version: int | None) -> dict[str, Any]: ...
    def get_metadata(self, workspace_id: int) -> dict[str, Any] | None: ...
    def save_metadata(self, workspace_id: int, metadata: dict[str, Any]) -> dict[str, Any]: ...
    def get_chat(self, workspace_id: int) -> dict[str, Any]: ...
    def save_chat(self, workspace_id: int, user_id: int, payload: dict[str, Any]) -> dict[str, Any]: ...

    def get_sync_log(self, workspace_id: int, client_id: str, batch_id: str) -> dict[str, Any] | None: ...
    def create_sync_log(self, workspace_id: int, user_id: int, client_id: str, batch_id: str, status: str, details: dict[str, Any]) -> None: ...
    def list_sync_logs(self, workspace_id: int, page: int, page_size: int) -> tuple[list[dict[str, Any]], int]: ...
    def bump_workspace_sync_version(self, workspace_id: int) -> int: ...
