/**
 * parseAgentsMd.test.ts — client-side agents.md roster parser.
 *
 * Must stay in lockstep with the server parser
 * (devsphere_ai/spec_driven/parsers.py::parse_agents): same frontmatter
 * fences, same required keys, same csv handling for tools/tasks.
 */

import { describe, it, expect } from "vitest";
import { parseAgentsMd, parseSkillMd, parseSkillsMd } from "@/lib/devsphere-agent-api";

const SAMPLE = `# Custom Agents

Generated by the agents phase (gate 4).

---
name: fullstack-implementer
description: Implements features end to end
tools: file_write, run_terminal
tasks: T001, T002
---
You are a fullstack implementer. Build things.

---
name: verification-and-docs-engineer
description: End-to-end verification and artifact generation
tools: file_read
tasks: T003
---
Verify everything.
`;

describe("parseAgentsMd", () => {
  it("parses every frontmatter block into a SpecAgent", () => {
    const agents = parseAgentsMd(SAMPLE);
    expect(agents).toHaveLength(2);
    expect(agents[0]).toEqual({
      name: "fullstack-implementer",
      description: "Implements features end to end",
      tools: ["file_write", "run_terminal"],
      skills: [],
      tasks: ["T001", "T002"],
      system_prompt: "You are a fullstack implementer. Build things.",
      // Identity fields — empty when the file declares none, which is the
      // common case for a generated roster block.
      persona: "",
      title: "",
      icon: "",
      when_to_use: "",
    });
    expect(agents[1].name).toBe("verification-and-docs-engineer");
    expect(agents[1].tasks).toEqual(["T003"]);
  });

  it("skips blocks missing name or description (hand-edited files)", () => {
    const agents = parseAgentsMd("---\ntools: file_read\n---\nno name here\n");
    expect(agents).toEqual([]);
  });

  it("ignores comment lines and handles CRLF line endings", () => {
    const crlf = "---\r\n# a comment\r\nname: a\r\ndescription: b\r\n---\r\nprompt\r\n";
    const agents = parseAgentsMd(crlf);
    expect(agents).toHaveLength(1);
    expect(agents[0]).toMatchObject({ name: "a", description: "b", tools: [], tasks: [] });
    expect(agents[0].system_prompt).toBe("prompt");
  });

  it("returns [] for empty or fence-less content", () => {
    expect(parseAgentsMd("")).toEqual([]);
    expect(parseAgentsMd("just some markdown, no agents")).toEqual([]);
  });

  it("strips a leading BOM so a fence at file start still parses", () => {
    const bom = "﻿---\nname: a\ndescription: b\n---\nprompt\n";
    expect(parseAgentsMd(bom)).toHaveLength(1);
  });
});

/* ── Identity + open kinds (mirrors backend/tests/test_skill_catalog.py) ──
   The client is the PRIMARY scanner for a local workspace, so these parsers
   have to agree with the server's or an imported framework looks different
   depending on which side read it. */

describe("persona identity", () => {
  it("reads the human name from frontmatter", () => {
    const [agent] = parseAgentsMd(
      "---\nname: lead\ndescription: d\npersona: Winston\ntitle: Principal Engineer\nicon: 🛠️\n---\nbody\n",
    );
    expect(agent.persona).toBe("Winston");
    expect(agent.title).toBe("Principal Engineer");
    expect(agent.icon).toBe("🛠️");
  });

  it("falls back to the body's opening H1, the way BMAD v6 writes it", () => {
    const [agent] = parseAgentsMd("---\nname: analyst\ndescription: d\n---\n# Mary\n\nHello.\n");
    expect(agent.persona).toBe("Mary");
  });

  it("does not mistake a shell comment in a code fence for a name", () => {
    const [agent] = parseAgentsMd(
      "---\nname: a\ndescription: d\n---\nSome prose.\n\n```bash\n# Start dev server\nnpm run dev\n```\n",
    );
    expect(agent.persona).toBe("");
  });

  it("does not mistake a long document title for a name", () => {
    const [agent] = parseAgentsMd(
      "---\nname: a\ndescription: d\n---\n# Migration Runbook For The Payments Service\n",
    );
    expect(agent.persona).toBe("");
  });
});

describe("parseSkillMd / parseSkillsMd", () => {
  it("keeps whatever kind the file declares", () => {
    expect(parseSkillMd("---\nname: r\ndescription: d\ntype: orchestration\n---\nb", "f")?.kind)
      .toBe("orchestration");
    expect(parseSkillMd("---\nname: r\ndescription: d\ntype: my-own-kind\n---\nb", "f")?.kind)
      .toBe("my-own-kind");
    expect(parseSkillMd("---\nname: r\ndescription: d\n---\nb", "f")?.kind).toBe("skill");
  });

  it("reads every block of a stacked skills.md", () => {
    const skills = parseSkillsMd(
      "---\nname: one\ndescription: first\n---\nb1\n---\nname: two\ndescription: second\n---\nb2\n",
    );
    expect(skills.map((s) => s.name)).toEqual(["one", "two"]);
    expect(skills[1].description).toBe("second");
  });

  it("skips blocks with no name", () => {
    expect(parseSkillsMd("---\ndescription: nameless\n---\nbody\n")).toEqual([]);
  });
});

/* ── BMAD v6 stubs (the shape a real install drops in) ────────────────────
   `.devaccel/agents/bmad-agent-analyst.agent.md` carries `description:` and
   NOTHING else — the name is the filename and the body points at the
   canonical SKILL.md. parseAgentsMd rightly rejects it as an agent BLOCK;
   the caller must then fall back to the stub treatment. Requiring
   name+description and stopping there silently discarded every agent in a
   BMAD install. */

describe("description-only stubs", () => {
  const STUB = `---
description: Strategic business analyst. Use when the user asks to talk to Mary.
---

LOAD the FULL {project-root}/.agents/skills/bmad-agent-analyst/SKILL.md and follow it.
`;

  it("is not an agent block", () => {
    expect(parseAgentsMd(STUB)).toEqual([]);
  });

  it("still yields a description and a body via parseSkillMd", () => {
    const meta = parseSkillMd(STUB, "bmad-agent-analyst");
    expect(meta?.name).toBe("bmad-agent-analyst");
    expect(meta?.description).toContain("business analyst");
    expect(meta?.instructions).toContain("LOAD the FULL");
  });

  it("a full agent profile in the same folder still parses as one", () => {
    const full = `---
name: java-python-migrator
persona: Priya
description: Migrates Java to Python. Use when the user asks to talk to Priya.
skills: java-python-translation
---

# Priya
`;
    const [agent] = parseAgentsMd(full);
    expect(agent.name).toBe("java-python-migrator");
    expect(agent.persona).toBe("Priya");
    expect(agent.skills).toEqual(["java-python-translation"]);
  });
});

/* ── Hand-written files without `---` fences ──────────────────────────────
   Someone typing an agent by hand writes the fields they were shown and not
   necessarily the delimiters around them. The file is unmistakably a
   definition, so rejecting it over punctuation just made the agent vanish
   from the picker with no explanation. */

describe("fence-less frontmatter", () => {
  const FENCELESS = [
    "name: python-to-golang-migrator",
    "persona:Amar",                       // no space after the colon
    "title: Principal Python-to-golang Migration Engineer",
    "description: Owns Python to golang migrations. Talk to Amar.",
    "skills: java-python-migration",
    "",
    "# Amar",
    "Body text.",
  ].join("\r\n");                          // CRLF, as a Windows editor writes

  it("parses as an agent", () => {
    const [agent] = parseAgentsMd(FENCELESS);
    expect(agent.name).toBe("python-to-golang-migrator");
    expect(agent.persona).toBe("Amar");
    expect(agent.title).toBe("Principal Python-to-golang Migration Engineer");
    expect(agent.skills).toEqual(["java-python-migration"]);
  });

  it("keeps the body separate from the keys", () => {
    const [agent] = parseAgentsMd(FENCELESS);
    expect(agent.system_prompt).toContain("Body text.");
    expect(agent.system_prompt).not.toContain("name:");
  });

  it("does not turn ordinary prose into a definition", () => {
    expect(parseAgentsMd("Note: this is a document.\nAuthor: someone\n")).toEqual([]);
    expect(parseAgentsMd("# Heading\n\nSome prose.\n")).toEqual([]);
    // A single key is not a frontmatter block.
    expect(parseAgentsMd("name: lonely\n")).toEqual([]);
  });

  it("still prefers real fences when they are present", () => {
    const [agent] = parseAgentsMd("---\nname: fenced\ndescription: d\n---\nbody\n");
    expect(agent.name).toBe("fenced");
  });
});
